# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_fav', models.DateTimeField(null=True)),
                ('date_runner_up', models.DateTimeField(null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
                ('gender', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
                ('actors', models.ManyToManyField(to='videos.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('path_to_file', models.CharField(max_length=500)),
                ('path_to_dir', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_fav', models.DateTimeField(null=True)),
                ('date_runner_up', models.DateTimeField(null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SceneTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
                ('scenes', models.ManyToManyField(to='videos.Scene')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='scenes',
            field=models.ManyToManyField(to='videos.Scene'),
        ),
    ]
