# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_fav', models.DateTimeField(blank=True, null=True)),
                ('date_runner_up', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=15)),
                ('imdb_id', models.CharField(blank=True, max_length=25, null=True)),
                ('tmdb_id', models.CharField(blank=True, max_length=25, null=True)),
                ('official_pages', models.TextField(blank=True, default='')),
                ('ethnicity', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=30, null=True)),
                ('tattoos', models.CharField(blank=True, max_length=600, null=True)),
                ('piercings', models.CharField(blank=True, max_length=600, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('measurements', models.CharField(blank=True, max_length=30, null=True)),
                ('extra_text', models.TextField(blank=True, default='')),
                ('last_lookup', models.DateTimeField(blank=True, null=True)),
                ('is_exempt_from_one_word_search', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_exempt_from_one_word_search', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_fav', models.DateTimeField(blank=True, null=True)),
                ('date_runner_up', models.DateTimeField(blank=True, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('actor_tag_alias', models.TextField(blank=True, default='')),
                ('exclusions', models.TextField(blank=True, default='', null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('last_folder_name_only', models.CharField(max_length=100, null=True)),
                ('path_with_ids', models.CharField(blank=True, max_length=900, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='videos.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalSceneFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=32)),
                ('path_to_file', models.CharField(max_length=500, unique=True)),
                ('path_to_dir', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_fav', models.DateTimeField(blank=True, null=True)),
                ('date_last_played', models.DateTimeField(blank=True, null=True)),
                ('date_runner_up', models.DateTimeField(blank=True, null=True)),
                ('last_filename_tag_lookup', models.DateTimeField(blank=True, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bit_rate', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('codec_name', models.CharField(blank=True, max_length=20, null=True)),
                ('framerate', models.FloatField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, null=True, related_name='scenes', to='videos.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='SceneTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('date_fav', models.DateTimeField(blank=True, null=True)),
                ('date_runner_up', models.DateTimeField(blank=True, null=True)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('scene_tag_alias', models.TextField(blank=True, default='')),
                ('exclusions', models.TextField(blank=True, default='', null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('date_fav', models.DateTimeField(blank=True, null=True)),
                ('date_runner_up', models.DateTimeField(blank=True, null=True)),
                ('is_fav', models.BooleanField(default=False)),
                ('is_runner_up', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('website_alias', models.TextField(blank=True, default='')),
                ('exclusions', models.TextField(blank=True, default='', null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('scene_tags', models.ManyToManyField(blank=True, null=True, related_name='websites', to='videos.SceneTag')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='scenes', to='videos.SceneTag'),
        ),
        migrations.AddField(
            model_name='scene',
            name='websites',
            field=models.ManyToManyField(blank=True, null=True, related_name='scenes', to='videos.Website'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='scenes',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='videos.Scene'),
        ),
        migrations.AddField(
            model_name='folder',
            name='scenes',
            field=models.ManyToManyField(null=True, related_name='folders_in_tree', to='videos.Scene'),
        ),
        migrations.AddField(
            model_name='actortag',
            name='scene_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='actor_tags', to='videos.SceneTag'),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_aliases',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='videos.ActorAlias'),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='videos.ActorTag'),
        ),
    ]
