# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actortag',
            name='exclusions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='scenetag',
            name='exclusions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
