# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-25 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200524_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='exclusions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
