# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160613_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='actor',
            name='scenes',
            field=models.ManyToManyField(blank=True, null=True, to='videos.Scene'),
        ),
        migrations.AlterField(
            model_name='scenetag',
            name='scenes',
            field=models.ManyToManyField(blank=True, null=True, to='videos.Scene'),
        ),
    ]
