# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20160615_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='actoralias',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Actor'),
        ),
    ]
