# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20160616_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
