# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20160617_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='official_pages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
