# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20160617_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actortag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
