# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20160617_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actortag',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='scenetag',
            name='scenes',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_tags',
            field=models.ManyToManyField(null=True, to='videos.ActorTag'),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_tags',
            field=models.ManyToManyField(null=True, to='videos.SceneTag'),
        ),
    ]
