# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20160621_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country_of_origin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='ethnicity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='extra_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actor',
            name='height',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='measurements',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='tattoos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='weight',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
