# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_auto_20160623_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='scenes',
        ),
        migrations.AddField(
            model_name='scene',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='videos.Actor'),
        ),
    ]
