# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_auto_20160624_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='scene_tags',
            field=models.ManyToManyField(blank=True, null=True, to='videos.SceneTag'),
        ),
    ]
