# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='path_to_file',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
