# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20160627_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSceneFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='is_exempt_from_one_word_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actoralias',
            name='is_exempt_from_one_word_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actoralias',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
