# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_auto_20160630_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_aliases',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_aliases',
            field=models.ManyToManyField(blank=True, null=True, to='videos.ActorAlias'),
        ),
    ]
