# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_auto_20160630_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='last_folder_name_only',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
