# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_folder_last_folder_name_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_aliases',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='videos.ActorAlias'),
        ),
    ]
