# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_auto_20160704_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='videos.ActorTag'),
        ),
    ]
