# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_auto_20160707_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='scenes', to='videos.Actor'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='scenes', to='videos.SceneTag'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='websites',
            field=models.ManyToManyField(blank=True, null=True, related_name='scenes', to='videos.Website'),
        ),
        migrations.AlterField(
            model_name='website',
            name='scene_tags',
            field=models.ManyToManyField(null=True, related_name='websites', to='videos.SceneTag'),
        ),
    ]
