# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_auto_20160717_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='tattoos',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
