# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_auto_20160720_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='bit_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='codec_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
