# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_auto_20160727_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='framerate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
