# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_auto_20160730_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
