# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_scene_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='path_with_ids',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
