# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-02-22 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_models_piercings_videohasher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='piercings',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='hash',
            field=models.CharField(blank=True, max_length=32),
            preserve_default=False,
        ),
    ]
