version: '2'
services:
  yapo:
    image: cooperdk/yapo-eplus:latest-amd64
    #build: .
    network_mode: host
    ports:
      - "8000:8000"
      # YAPO defaults to 127.0.0.1:8000 but this is configurable.
      # Change the above ports AFTER you edit listen IP:port in settings!
    volumes:
      - ../:/YAPO
      # Add any video sources below, in the format (localfolder):(folder in Docker container).
      # On Windows, you must forward slash any backslashes, fx "c:/videos".
      # Team YAPO recommends that you map videos to any Docker rootfolder and issue unique subfolders,
      # like: "C:/videos:/videos/c-drive-videos".
      #
      # REMEMBER: All paths with spaces MUST be quoted. Like: "C:/Video Files":"/videos/C-drive Video Files"
      # Your lines must begin with a hyphen EXACTLY below the hash sign (6 spaces before the first character)
